kube:
  commands:
    - match: .*/Chart\.ya?ml
      command: helm
      args:
        - template
        - .
        - --generate-name
    - match: .*/kustomization\.ya?ml
      command: kustomize
      args:
        - build
        - .
ui:
  keybinds:
    common:
      quit:
        description: quit
        keys:
          - code: q
          - code: ctrl+c
            alias: ⌃c
            hidden: true
      suspend:
        description: suspend
        keys:
          - code: ctrl+z
            alias: ⌃z
            hidden: true
      reload:
        description: reload
        keys:
          - code: r
      help:
        description: toggle help
        keys:
          - code: "?"
      error:
        description: toggle error
        keys:
          - code: "!"
      escape:
        description: go back
        keys:
          - code: esc
      up:
        description: move up
        keys:
          - code: up
            alias: ↑
          - code: k
      down:
        description: move down
        keys:
          - code: down
            alias: ↓
          - code: j
      left:
        description: move left
        keys:
          - code: left
            alias: ←
          - code: h
      right:
        description: move right
        keys:
          - code: right
            alias: →
          - code: l
      prev:
        description: previous page
        keys:
          - code: shift+tab
            alias: ⇧+tab
          - code: H
      next:
        description: next page
        keys:
          - code: tab
          - code: L
    stash:
      open:
        description: open
        keys:
          - code: enter
            alias: ↵
      find:
        description: find
        keys:
          - code: /
      home:
        description: go to start
        keys:
          - code: home
          - code: g
      end:
        description: go to end
        keys:
          - code: end
          - code: G
    pager:
      copy:
        description: copy contents
        keys:
          - code: c
      home:
        description: go to top
        keys:
          - code: home
          - code: g
      end:
        description: go to bottom
        keys:
          - code: end
          - code: G
      pageUp:
        description: page up
        keys:
          - code: pgup
          - code: b
      pageDown:
        description: page down
        keys:
          - code: pgdn
          - code: f
      halfPageUp:
        description: ½ page up
        keys:
          - code: u
      halfPageDown:
        description: ½ page down
        keys:
          - code: d
  minimum-delay: 500ms
  glamour-style: auto
  glamour-max-width: 0
  glamour-disabled: false
  show-line-numbers: true
  compact: false
