# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: kat

env:
  - DOCKER_REGISTRY=ghcr.io/macropower

release:
  prerelease: auto

before:
  hooks:
    - bash gen.sh

builds:
  - id: kat
    main: ./cmd/kat
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/macropower/kat/pkg/version.Version={{.Version}}
      - -X github.com/macropower/kat/pkg/version.Branch={{.Branch}}
      - -X github.com/macropower/kat/pkg/version.BuildUser={{.Env.USER}}@{{.Env.HOSTNAME}}
      - -X github.com/macropower/kat/pkg/version.BuildDate={{.Date}}
    flags:
      - -trimpath

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - completion/**/*
      - man/*

gomod:
  proxy: true

checksum:
  name_template: "checksums.txt"

source:
  enabled: true
  name_template: "{{ .ProjectName }}"

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

# https://goreleaser.com/customization/sign
signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
    output: true

notarize:
  # https://goreleaser.com/customization/notarize/#cross-platform
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      sign:
        certificate: "{{.Env.MACOS_SIGN_P12}}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"
        entitlements: resources/entitlements.xml
      notarize:
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
        key: "{{.Env.MACOS_NOTARY_KEY}}"
        wait: true
        timeout: 30m

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

homebrew_casks:
  - name: kat
    conflicts:
      - formula: kat
    repository:
      owner: MacroPower
      name: homebrew-tap
    url:
      template: &archiveTemplate >-
        https://github.com/MacroPower/kat/releases/download/{{ .Tag }}/
        {{- .ProjectName }}_
        {{- title .Os }}_
        {{- if eq .Arch "amd64" }}x86_64
        {{- else if eq .Arch "386" }}i386
        {{- else }}{{ .Arch }}{{ end -}}
        {{- if .Arm }}v{{ .Arm }}{{ end -}}
        .tar.gz
    commit_msg_template: "chore: formula update for kat {{ .Tag }}"
    commit_author: &commitAuthor
      name: botty-mcbottington
      email: 168950816+botty-mcbottington[bot]@users.noreply.github.com
    homepage: &homepage "https://github.com/MacroPower/kat/"
    description: &description "TUI for rendering, validating, and displaying local Kubernetes manifests"
    license: "Apache 2.0"
    skip_upload: auto
    manpages:
      - man/kat.1
    completions:
      bash: completion/bash/kat.bash
      zsh: completion/zsh/_kat
      fish: completion/fish/kat.fish

nix:
  - name: kat
    repository:
      owner: MacroPower
      name: nur-packages
    url_template: *archiveTemplate
    commit_msg_template: "chore: pkg update for kat {{ .Tag }}"
    commit_author: *commitAuthor
    homepage: *homepage
    description: *description
    license: "asl20"
    skip_upload: auto
    extra_install: |
      installManPage ./man/kat.1
      installShellCompletion ./completion/bash/kat.bash
      installShellCompletion ./completion/zsh/_kat
      installShellCompletion ./completion/fish/kat.fish

docker_manifests:
  - name_template: '{{ .Env.DOCKER_REGISTRY }}/{{ .ProjectName }}:{{ .Tag }}'
    image_templates: &baseImageTemplates
      - '{{ .Env.DOCKER_REGISTRY }}/{{ .ProjectName }}:{{ .Tag }}-amd64'
      - '{{ .Env.DOCKER_REGISTRY }}/{{ .ProjectName }}:{{ .Tag }}-arm64'
    skip_push: false
  - name_template: '{{ .Env.DOCKER_REGISTRY }}/{{ .ProjectName }}:latest'
    image_templates: *baseImageTemplates
    skip_push: auto
  - name_template: '{{ .Env.DOCKER_REGISTRY }}/{{ .ProjectName }}:v{{ .Major }}'
    image_templates: *baseImageTemplates
    skip_push: auto
  - name_template: '{{ .Env.DOCKER_REGISTRY }}/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}'
    image_templates: *baseImageTemplates
    skip_push: auto

  - name_template: '{{ .Env.DOCKER_REGISTRY }}/{{ .ProjectName }}:{{ .Tag }}-alpine'
    image_templates: &alpineImageTemplates
      - '{{ .Env.DOCKER_REGISTRY }}/{{ .ProjectName }}:{{ .Tag }}-alpine-amd64'
      - '{{ .Env.DOCKER_REGISTRY }}/{{ .ProjectName }}:{{ .Tag }}-alpine-arm64'
    skip_push: false
  - name_template: '{{ .Env.DOCKER_REGISTRY }}/{{ .ProjectName }}:latest-alpine'
    image_templates: *alpineImageTemplates
    skip_push: auto
  - name_template: '{{ .Env.DOCKER_REGISTRY }}/{{ .ProjectName }}:v{{ .Major }}-alpine'
    image_templates: *alpineImageTemplates
    skip_push: auto
  - name_template: '{{ .Env.DOCKER_REGISTRY }}/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-alpine'
    image_templates: *alpineImageTemplates
    skip_push: auto

  - name_template: '{{ .Env.DOCKER_REGISTRY }}/{{ .ProjectName }}:{{ .Tag }}-debian'
    image_templates: &debianImageTemplates
      - '{{ .Env.DOCKER_REGISTRY }}/{{ .ProjectName }}:{{ .Tag }}-debian-amd64'
      - '{{ .Env.DOCKER_REGISTRY }}/{{ .ProjectName }}:{{ .Tag }}-debian-arm64'
    skip_push: false
  - name_template: '{{ .Env.DOCKER_REGISTRY }}/{{ .ProjectName }}:latest-debian'
    image_templates: *debianImageTemplates
    skip_push: auto
  - name_template: '{{ .Env.DOCKER_REGISTRY }}/{{ .ProjectName }}:v{{ .Major }}-debian'
    image_templates: *debianImageTemplates
    skip_push: auto
  - name_template: '{{ .Env.DOCKER_REGISTRY }}/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-debian'
    image_templates: *debianImageTemplates
    skip_push: auto

dockers:
  - goos: linux
    goarch: amd64
    dockerfile: docker/Dockerfile
    use: buildx
    image_templates:
      - "{{ .Env.DOCKER_REGISTRY }}/{{ .ProjectName }}:{{ .Tag }}-amd64"
    build_flag_templates: &amd64DockerBuildFlags
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Tag }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
  - goos: linux
    goarch: arm64
    dockerfile: docker/Dockerfile
    use: buildx
    image_templates:
      - "{{ .Env.DOCKER_REGISTRY }}/{{ .ProjectName }}:{{ .Tag }}-arm64"
    build_flag_templates: &arm64DockerBuildFlags
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Tag }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
  - goos: linux
    goarch: arm64
    dockerfile: docker/Dockerfile.alpine
    use: buildx
    image_templates:
      - "{{ .Env.DOCKER_REGISTRY }}/{{ .ProjectName }}:{{ .Tag }}-alpine-arm64"
    extra_files:
      - completion/
      - man/
    build_flag_templates: *arm64DockerBuildFlags
  - goos: linux
    goarch: amd64
    dockerfile: docker/Dockerfile.alpine
    use: buildx
    image_templates:
      - "{{ .Env.DOCKER_REGISTRY }}/{{ .ProjectName }}:{{ .Tag }}-alpine-amd64"
    extra_files:
      - completion/
      - man/
    build_flag_templates: *amd64DockerBuildFlags
  - goos: linux
    goarch: arm64
    dockerfile: docker/Dockerfile.debian
    use: buildx
    image_templates:
      - "{{ .Env.DOCKER_REGISTRY }}/{{ .ProjectName }}:{{ .Tag }}-debian-arm64"
    build_flag_templates: *arm64DockerBuildFlags
  - goos: linux
    goarch: amd64
    dockerfile: docker/Dockerfile.debian
    use: buildx
    image_templates:
      - "{{ .Env.DOCKER_REGISTRY }}/{{ .ProjectName }}:{{ .Tag }}-debian-amd64"
    build_flag_templates: *amd64DockerBuildFlags

docker_signs:
  - cmd: cosign
    artifacts: images
    output: true
    args:
      - "sign"
      - "${artifact}@${digest}"
      - "--yes"
